;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/Data/DataTables/DT_ObjectiveTagTable.DT_ObjectiveTagTable
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Core_Adamant",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Core_CeramicSkin",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Core_Reactive",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Grip_Pulse",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Grip_Servo",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Grip_Tension",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Neuro_Aegis",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Neuro_Bastion",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Neuro_Shell",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Stride_Kinetic",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Stride_Reflex",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Stride_Traction",DevComment="")
+GameplayTagList=(Tag="Item.Material.BioSample",DevComment="")
+GameplayTagList=(Tag="Item.Material.ChemicalCompound",DevComment="")
+GameplayTagList=(Tag="Item.Material.ElectronicPart",DevComment="")
+GameplayTagList=(Tag="Item.Material.ReinforcedFiber",DevComment="")
+GameplayTagList=(Tag="Item.Material.ScrapPart",DevComment="")
+GameplayTagList=(Tag="Item.Misc.AncientRelic",DevComment="")
+GameplayTagList=(Tag="Item.Misc.BrokenDataChip",DevComment="")
+GameplayTagList=(Tag="Item.Misc.NovadeaArtifact",DevComment="")
+GameplayTagList=(Tag="Item.Misc.NovadeaDogTag",DevComment="")
+GameplayTagList=(Tag="Item.Misc.PortableCalculator",DevComment="")
+GameplayTagList=(Tag="Item.Misc.ScrapMetal",DevComment="")
+GameplayTagList=(Tag="Item.Misc.SmallEnergyCell",DevComment="")
+GameplayTagList=(Tag="Item.Misc.SubjectRecordCard",DevComment="")
+GameplayTagList=(Tag="Item.Misc.SupplyCigarettes",DevComment="")
+GameplayTagList=(Tag="Item.Quest.AcidResistantCarapace",DevComment="")
+GameplayTagList=(Tag="Item.Quest.ArgosRedEyeLens",DevComment="")
+GameplayTagList=(Tag="Item.Quest.ContaminatedBioSample",DevComment="")
+GameplayTagList=(Tag="Item.Quest.EncryptedOpsMap",DevComment="")
+GameplayTagList=(Tag="Item.Quest.ExperimentJournal",DevComment="")
+GameplayTagList=(Tag="Item.Quest.FalseathersLetter",DevComment="")
+GameplayTagList=(Tag="Item.Quest.OldUnitJournal",DevComment="")
+GameplayTagList=(Tag="Item.Quest.ResidentDataLog",DevComment="")
+GameplayTagList=(Tag="Item.Quest.ShardLabCoordinates",DevComment="")
+GameplayTagList=(Tag="Item.Quest.SpiralJetMuscle",DevComment="")
+GameplayTagList=(Tag="Item.Quest.WeaponBlueprint",DevComment="")
+GameplayTagList=(Tag="Item.Quest.ZephyrosAmpCircuit",DevComment="")
+GameplayTagList=(Tag="Item.Storage.BasicBag",DevComment="")
+GameplayTagList=(Tag="Item.Storage.DefaultBag",DevComment="")
+GameplayTagList=(Tag="Item.Storage.SecureContainer",DevComment="")
+GameplayTagList=(Tag="Item.Storage.SecureContainerPlus",DevComment="")
+GameplayTagList=(Tag="Item.Storage.SpecialBag",DevComment="")
+GameplayTagList=(Tag="Item.Storage.TacticalBag",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.Adrenaline",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.Bandage",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.CombatRation",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.GelKit",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.KineticBooster",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.NanoSutureKit",DevComment="")
+GameplayTagList=(Tag="Item.Supplies.PurifiedWater",DevComment="")
+GameplayTagList=(Tag="Item.Throwables.Flashbang",DevComment="")
+GameplayTagList=(Tag="Item.Throwables.Grenade",DevComment="")
+GameplayTagList=(Tag="Item.Throwables.SmokeGrenade",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Kestrel",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Kestrel1",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Kestrel2",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Kestrel3",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Owl",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Owl1",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Owl2",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Owl3",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Raven",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Raven1",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Raven2",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Raven3",DevComment="")
+GameplayTagList=(Tag="Item.Weapon_Firearm.Sparrow",DevComment="")
+GameplayTagList=(Tag="Monster.Boss.Argus",DevComment="")
+GameplayTagList=(Tag="Monster.Boss.SpineQueen",DevComment="")
+GameplayTagList=(Tag="Monster.Normal.Frog",DevComment="")
+GameplayTagList=(Tag="NPC.Commander",DevComment="")
+GameplayTagList=(Tag="NPC.M224",DevComment="어스")
+GameplayTagList=(Tag="NPC.Ned",DevComment="")
+GameplayTagList=(Tag="NPC.Nemo",DevComment="")
+GameplayTagList=(Tag="NPC.SessionNPC",DevComment="")
+GameplayTagList=(Tag="NPC.Shaad",DevComment="")
+GameplayTagList=(Tag="NPC.Tau",DevComment="")
+GameplayTagList=(Tag="NPC.TestNPC",DevComment="")
+GameplayTagList=(Tag="NPC.Uni",DevComment="")
+GameplayTagList=(Tag="Quest.ID.Main.AccessRights",DevComment="첫번째 퀘스트입니다")
+GameplayTagList=(Tag="Quest.ID.Main.Boss1",DevComment="")
+GameplayTagList=(Tag="Quest.ID.Main.CorrosiveTrap",DevComment="세번째 퀘스트입니다. ")
+GameplayTagList=(Tag="Quest.ID.Main.DesignersLegacy",DevComment="두번째 퀘스트입니다. ")
+GameplayTagList=(Tag="Quest.ID.Main.Ending",DevComment="엔딩 퀘스트입니다")
+GameplayTagList=(Tag="Quest.ID.Main.MothersNest",DevComment="4번째 퀘스트입니다")
+GameplayTagList=(Tag="Quest.ID.Main.Prologue",DevComment="게임 시작 직후 시작되는 프롤로그 입니다")
+GameplayTagList=(Tag="Quest.ID.Main.TEST",DevComment="")
+GameplayTagList=(Tag="Quest.ID.Main.TraitorsTrace",DevComment="5번째 퀘스트입니다. ")
+GameplayTagList=(Tag="Quest.ID.Main.VoidRevenge",DevComment="6번째 퀘스트입니다.")
+GameplayTagList=(Tag="Quest.ID.Sub.AccessAuth",DevComment="")
+GameplayTagList=(Tag="Quest.ID.Sub.Legacy",DevComment="")
+GameplayTagList=(Tag="Quest.ID.Sub.SlyFrog",DevComment="")
+GameplayTagList=(Tag="test",DevComment="")

